# Plugins
plugins:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']
future: true # Enable future posts (date > current date)


# Site Settings
title: "Research Bazaar Victoria"
email: "mailto:ResBazVIC-l@monash.edu"
description: "Run by a team from Monash eResearch, Research Bazaar (ResBaz for short) is a skill- and community-building festival where HDR students and early career researchers come together to learn the latest in digital research tools and digital scholarship."
baseurl: "/resbazvic2024"
# url: "https://resbaz.github.io/resbaz2024victoria/"
url: "https://resbaz.github.io/resbazvic2024/" 
permalink: "/blog/:title"
#googleAnalyticsTrackingId: "UA-43643469-5"
#googleAnalyticsSiteUrl: "matty-plumski.github.io"
#siteVerification: "xOlzoaCacKCBpEsxW4st40F89pI="


# Organizer Info
organizerName: "Angelika Dibijo"
organizerAlternateName: "Monash"
# organizerDescription: " "
organizerEmail: "ResBazVIC-l@monash.edu" 
organizerLogo: ""
organizerLink: "https://www.monash.edu/researchinfrastructure/eresearch"

# Head
metaKeywords: "event, resbaz, research, bazaar, victoria, melbourne, digital, skills, upskilling, hdr, ecr, eresearch, resbazvic, resbazmelb"
twitterAccount: "@MonasheResearch"
#instagramAccount: "@ResBazQld"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"

# Documents
c4pUrl: "mailto:ResBazVIC-l@monash.edu"
c4sponsorsUrl: "https://www.monash.edu/researchinfrastructure/eresearch"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
# - {permalink: "/registration/", text: "Register"}
# - {link: "https://events.humanitix.com/resbazqld-2023", text: "Register"}
# - {link: "https://www.eventbrite.com/o/monash-eresearch-centre-80527865623", text: "Register"}
 - {permalink: "/news/", text: "News"}
 - {link: "https://redcap.link/resbazvic2024", text: "Get involved"}
#  - {permalink: "/schedule/", text: "Program"}
 - {permalink: "/program/", text: "Program"}
#  - {permalink: "/speakers/", text: "Speakers"}
# - {permalink: "/sessions/", text: "Sessions"}
 - {permalink: "/transport/", text: "Location"}
#  - {permalink: "/partners/", text: "Partners & Sponsors"}
 - {permalink: "/codeofconduct/", text: "Code of Conduct"}
# rightNavigationButtons:
#  - {permalink: "/program/", text: "Program"}
#  - {link: "https://www.eventbrite.com.au/e/resbaz-sydney-2023-tickets-707597462057", text: "Register"}
 
 # - {link: "https://twitter.com/resbazqld", text: "Follow us for updates"}
   # bottomNavigationLinks:
  # - {link: "https://forms.gle/5Kc4QUkhibvuopA48", text: "Get involved - volunteer here!"}
#rightNavigationButtons:
# - {link: "https://forms.gle/5Kc4QUkhibvuopA48", text: "Get involved - volunteer here!"}


# Hero Block
heroImage: "melbourne.jpg"
heroTitle: "Research Bazaar Victoria"
eventDate: "Nov 26-28 2024"



# About Block
aboutTitle: "About ResBaz Victoria"
aboutSubtitle: "A festival of digital research"
aboutText: "
<p>Led by <a href='https://www.monash.edu/researchinfrastructure/eresearch/news/resbaz-2024'>Monash eResearch</a>, ResBaz will be held on November 26-28, 2024 at the Clayton campus. Join us for an engaging, in-person event that emphasises participation and collaboration!</p>

<p>The Research Bazaar is a dynamic forum designed to empower researchers with cutting-edge digital research tools and skills. Sessions at this year's ResBaz will offer a brief practical introduction to a broad selection of topics and tools related to digital research practice relevant across multiple disciplines.</p>

<p><b>We welcome researchers from ALL over Australia, at ALL levels, and from ALL disciplines! </b>
Whether you're a PhD candidate, a research master's student, an early career researcher, or a research technologist or software engineer supporting research, this event is for you.</p>

<br>

<p><b>ResBaz Vic 2024 registration is now open! </b> </p>
<p><b>Check the  <a href='https://resbaz.github.io/resbazvic2024/program/'>confirmed sessions</a> and register to secure your spot. </b></p>
"

# "<p>The Research Bazaar is a dynamic forum designed to empower researchers with cutting-edge digital research tools and skills. Much like a bustling marketplace or bazaar, ResBaz provides a vibrant platform where researchers from diverse disciplines converge to enhance their capabilities, exchange knowledge, and foster meaningful connections.</p>

# <p>ResBaz Victoria 2024 will be a face-to-face event hosted by the Monash University eResearch. With a strong emphasis on participation and collaboration, ResBaz offers an immersive experience where individuals can learn, share, and network, driving innovation and collaboration across the research community.</p>

# <p>Researchers at ALL levels from ALL disciplines are invited! PhD candidates, research master’s students and early career researchers are especially encouraged to attend. Research technologists and software engineers supporting researchers to do their jobs should also come along!</p>

# <p>Sessions at this year's ResBaz will offer a brief practical introduction to a broad selection of topics and tools related to digital research practice relevant across the disciplines.</p>"

# <p>ResBaz Victoria 2024 will be a face-to-face event hosted by the Monash University eResearch. With a strong emphasis on participation and collaboration, ResBaz offers an immersive experience where individuals can learn, share, and network, driving innovation and collaboration across the research community.</p>

# <p>Researchers at ALL levels from ALL disciplines are invited! PhD candidates, research master’s students and early career researchers are especially encouraged to attend. Research technologists and software engineers supporting researchers to do their jobs should also come along!</p>




# Statistic Block
# statisticBlockImage: "statistic.jpg"
# statisticBlock:
#  - {count: "100", specialCharacter: "+", info: "attendees", detail: ""}
#  - {count: "50", specialCharacter: "+", info: "hours", detail: ""}
#  - {count: "25", specialCharacter: "+", info: "speakers", detail: ""}
#  - {count: "3", specialCharacter: "", info: "parallel streams", detail: ""}

# Latest News Block
# latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "Wattle_ResbazQld_NathCampus.jpg"
rockstarSpeakersCount: 3
rockstarSpeakersTitle: "Keystory speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
# locationBlockTitle: "Location"
# eventLocationName: "Learning and Teaching Building, Monash University Clayton"
# eventLocationLink: "https://maps.app.goo.gl/CnW7cjSEtHyMy5pT8"
# eventStreetAddress: "19 Ancora Imparo Wy"
# eventAddressLocality: "Monash University - Clayton Campus"
# eventAddressLocalityRegion: "Clayton, VIC"
# eventPostalCode: "3168"
# eventAddressCountry: "Australia"
# eventStartTime: "2024-11-26T09:00"
# eventDoorTime: "09:00"
# eventEndTime: "2024-11-28T17:00"
# eventPlaceCoordinates: "-27.497270750611534, 153.01185796853596"
# mapCenterCoordinates: "-27.497270750611534, 153.01185796853596"
# mapMobileCenterCoordinates: "-27.497270750611534, 153.01185796853596"
#
# Venue Block
# venueBlockTitle: "Past Events"
# venueBigImage: "wisteria.jpg"
# venueSmallImage2: "wisteria.jpg"
# venueSmallImage1: "wisteria.jpg"
# venueSmallImage3: "wisteria.jpg"
# venueTitle: "ResBaz 2022 "
# venueFeatures: ["Mix of online and in-person events", "Network and collaborate","Sessions streamed across Queensland"]

# Tweets Feed Block
# tweetsFeedImage: "PurpleF_ResbazQld_NathCampus.jpg"
# tweetsFeedTitle: "What's the latest?"
# twitterHashTag: "ResBazVic"
# twitterFeed: "https://twitter.com/MonasheResearch"

# Partners Block
organizersTitle: "Partners"
# partnersTitle: "Partners"
# partnersC4sponsorsButton: "See you next year!"
# partnersLink: ""

# Subscribe Block
# subscribeImage: "subscribe.jpg"
# subscribeTitle: "Subscribe for updates"
# subscribeAction: "https://docs.google.com/forms/d/e/1FAIpQLSfTwkZaRlKULFQrnY66P2MJSpYeUyS2eJ3RPcqMDNHy1QxmyA/viewform"
# subscribeInfo: ""

# Tickets Block
# ticketsTitle: "Pricetable"
# ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
# ticketsOffers: -
#  name: "Early Bird"
#   price: " "
#  priceCurrency: " "
#  ticketsNumber: " "
#  ribbon: "-5%"
#   buyButtonLink: " "
#  buyButtonText: " "
#  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
#  validFrom: "2014-08-25T10:00"
# validThrough: "2014-09-30T23:59"
#  -
#   name: "Last Chance"
#   price: " "
#  priceCurrency: " "
#   ticketsNumber: " "
#   ribbon: "-20%"
#  featured: true
#   buyButtonLink: " "
#   buyButtonText: "Buy Now"
#   ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
#  validFrom: "2014-10-01T00:00"
#   validThrough: "2014-10-23T23:59"
#   disabled: true
# -
#   name: "Student"
#   price: " "
#   priceCurrency: " "
#   ticketsNumber: " "
#   buyButtonLink: " /"
#   buyButtonText: "Buy Now"
#   additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
#   ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
#  validFrom: "2014-08-20T10:00"
#  validThrough: "2014-10-23T23:59"
#  soldOut: true
#   soldOutText: "Sold Out"

# Footer
socialLinks:
 - {link: "https://twitter.com/MonasheResearch", icon: "twitter"}
# - {link: "https://instagram.com/ResBazQld", icon: "instagram"}
# - {link: "https://www.linkedin.com/events/resbazqld7107577402066694145/comments/", icon: "linkedin"}
 - {link: "https://www.monash.edu/researchinfrastructure/eresearch", icon: "site"}
 - {link: "mailto:ResBazVIC-l@monash.edu", icon: "email"}

 # icon > hand > volunteer form 
footerBlocks:
 #-
  #title: "Links"
  #links:
   #- {link: "https://www.flickr.com/photos/bystandr/", text: "All site background images copyright Dr Nick"}
 -
  title: "National Sponsors"
  links:
  #  - {link: "https://www.gale.com/intl/primary-sources/digital-scholar-lab", text: "Gale", imageUrl: "../img/organizers/gale_trans.png"}
   - {link: "https://ardc.edu.au", text: "ARDC", imageUrl: "../img/organizers/ARDC_logo_RGB.png"}
 -
  title: "Gold Sponsors"
  links:
   - {link: "https://www.gale.com/intl/primary-sources/digital-scholar-lab", text: "Gale", imageUrl: "../img/organizers/gale_trans.png"}
#    - {link: "https://learningresources.sagepub.com/home", text: "SAGE Publications", imageUrl: "../img/organizers/sage2023.png"}
 -    
  title: "Silver Sponsor"
  links:
   - {link: "https://www.aarnet.edu.au/", text: "AARNet", imageUrl: "../img/organizers/aarnet.png"}
   - {link: "https://www.ddn.com/", text: "DDN", imageUrl: "../img/organizers/DDN.jpg"}
 -  
  title: "Collaborating Institutes"
  links:
   - {text: "Monash University", description: "Monash", link: "https://www.monash.edu/researchinfrastructure/eresearch", imageUrl: "../img/organizers/uq.jpg"}

 -  
  title: "Contacts for inquries"
  links:
   - {link: "mailto:ResBazVIC-l@monash.edu", text: "ResBazVIC-l@monash.edu"}
   - {link: "https://redcap.link/resbazvic2024", text: "Volunteer as a helper for ResBaz"}
#  - {link: "https://redcap.link/resbazvic2024", text: "Submit a workshop for ResBaz"} 
   - {link: "https://redcap.link/resbazvic2024", text: "Submit a poster for ResBaz Poster Session"} 
   
 -
  title: "FAQ"
  links:
   - {permalink: "/codeofconduct/", text: "Code of Conduct"}

# Blog
# blogTitle: "Latest news"
# blogCommentsEnabled: false
# discusShortName: "resbazqld"

# Speakers List Block
showSessions: true
showSpeakersBioFirst: true
